# Generated by Django 2.0.4 on 2018-04-26 19:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Chaves para Imagens de Satélite',
                'ordering': ('nome',),
                'verbose_name': 'Chave para Imagens de Satélite',
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Etiquetas para Imagens de Satélite',
                'ordering': ('nome',),
                'verbose_name': 'Etiqueta para Imagens de Satélite',
            },
        ),
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Missões para Observação da Terra',
                'ordering': ('nome',),
                'verbose_name': 'Missão para Observação da Terra',
            },
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4674, verbose_name='Selecionar ponto')),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4674, verbose_name='Selecionar polígono')),
                ('coll', django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4674, verbose_name='Selecionar local/is')),
                ('query_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da consulta')),
                ('req_min_date', models.DateField(blank=True, null=True, verbose_name='Data mínima desejada')),
                ('req_max_date', models.DateField(blank=True, null=True, verbose_name='Data máxima desejada')),
                ('chaves', models.ManyToManyField(blank=True, to='geobusca01_acre_app.Chave')),
                ('missoes', models.ManyToManyField(blank=True, to='geobusca01_acre_app.Missao')),
            ],
            options={
                'verbose_name_plural': 'Pontos em Sirgas 2000',
                'ordering': ('query_date',),
                'verbose_name': 'Ponto em Sirgas 2000',
            },
        ),
        migrations.CreateModel(
            name='Raster',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('acq_date', models.DateField(null=True, verbose_name='Data de aquisição')),
                ('acq_year', models.IntegerField(null=True, verbose_name='Ano de aquisição')),
                ('location', models.FileField(max_length=254, upload_to='', verbose_name='Endereço do arquivo')),
                ('src_srs', models.CharField(max_length=254, verbose_name='EPSG original')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4674)),
            ],
            options={
                'verbose_name_plural': 'Polígonos de Rasters em Sirgas 2000',
                'ordering': ('location',),
                'verbose_name': 'Polígono de Rasters em Sirgas 2000',
            },
        ),
        migrations.CreateModel(
            name='Satelite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('missao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geobusca01_acre_app.Missao')),
            ],
            options={
                'verbose_name_plural': 'Satélites',
                'ordering': ('nome',),
                'verbose_name': 'Satélite',
            },
        ),
        migrations.AddField(
            model_name='raster',
            name='satelite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geobusca01_acre_app.Satelite'),
        ),
        migrations.AddField(
            model_name='ponto',
            name='satelites',
            field=models.ManyToManyField(blank=True, to='geobusca01_acre_app.Satelite'),
        ),
        migrations.AddField(
            model_name='chave',
            name='etiquetas',
            field=models.ManyToManyField(to='geobusca01_acre_app.Etiqueta'),
        ),
    ]
